name: Azure Web App Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.USER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.USER_NAME }}/devops-app:${{ github.sha }} .
          docker push ${{ secrets.USER_NAME }}/devops-app:${{ github.sha }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App (Docker)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.USER_NAME }}/devops-app:${{ github.sha }}
