name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup zip file
        run: |
          zip -r app.zip .

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ZIP package to Azure Web App
        run: |
          az webapp deployment source config-zip \
            --resource-group multazim \
            --name multazimdev \
            --src app.zip
